mod as_bytes;
mod as_mut_bytes;
mod duration_to_ticks;
mod fmt_braced;
mod fmt_hyphenated;
mod fmt_simple;
mod fmt_urn;
mod from_bytes;
mod from_parts_dcom;
mod from_parts_ncs;
mod from_parts_v1;
mod from_parts_v2;
mod from_parts_v3;
mod from_parts_v4;
mod from_parts_v5;
mod from_parts_v6;
mod from_parts_v7;
mod from_parts_v8;
mod from_u128;
mod gen_dcom;
mod gen_ncs;
mod gen_v1;
mod gen_v2;
mod gen_v4;
mod gen_v6;
mod gen_v7;
mod get_clock_seq;
mod get_node_id;
mod get_timestamp;
mod get_variant;
mod get_version;
mod max;
mod new_dcom;
mod new_ncs;
mod new_v1;
mod new_v2;
mod new_v3;
mod new_v4;
mod new_v5;
mod new_v6;
mod new_v7;
mod new_v8;
mod nil;
mod predicates;
mod set_variant;
mod set_version;
mod system_time_to_ticks;
mod to_u128;
mod with_variant;
mod with_version;

pub use fmt_braced::Braced;
pub use fmt_hyphenated::Hyphenated;
pub use fmt_simple::Simple;
pub use fmt_urn::Urn;
pub use new_ncs::NcsUuidError;

/// The number of 100-nanosecond intervals between the `FILETIME` epoch
/// (1601-01-01T00:00:00Z) and the Unix epoch (1970-01-01T00:00:00Z).
pub(crate) const FILETIME_EPOCH_OFFSET: u64 = 116_444_736_000_000_000;
